// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GardenAPI.Migrations
{
    [DbContext(typeof(GardenAPIContext))]
    [Migration("20211102214706_UpdateSeeds")]
    partial class UpdateSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GardenAPI.Models.Seed", b =>
                {
                    b.Property<int>("SeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Companions")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DaysTillHarvest")
                        .HasColumnType("int");

                    b.Property<int>("DaysTillSprout")
                        .HasColumnType("int");

                    b.Property<string>("Enemies")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SeedName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SqFootPlant")
                        .HasColumnType("int");

                    b.Property<int>("WaterInterval")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SeedId");

                    b.ToTable("Seeds");

                    b.HasData(
                        new
                        {
                            SeedId = 1,
                            Companions = "carrot, catnip, celery, chamomile, corn, cucumber, marigold, nasturtium, oregano",
                            DaysTillHarvest = 80,
                            DaysTillSprout = 10,
                            Enemies = "chives, garlic, leek, onion",
                            Notes = "full sun, direct sow outdoors",
                            SeedName = "pole beans",
                            SqFootPlant = 4,
                            WaterInterval = 3,
                            Zone = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11"
                        },
                        new
                        {
                            SeedId = 2,
                            Companions = "basil, garlic, parsley, amaranth, carrot, borage, marigold, onion, sage, cucumber",
                            DaysTillHarvest = 85,
                            DaysTillSprout = 10,
                            Enemies = "cabbage, broccoli, fennel, corn, kale, dill, pepper, eggplant, potato, brussel sprouts, cauliflower, collards, kholrabi,",
                            Notes = "full sun, start indoors and transplant",
                            SeedName = "tomato",
                            SqFootPlant = 1,
                            WaterInterval = 1,
                            Zone = "5, 6, 7, 8, 9, 10, 11"
                        },
                        new
                        {
                            SeedId = 3,
                            Companions = "lettuce, tomato, carrot, onion, pepper, peas, cucumber, spinach",
                            DaysTillHarvest = 60,
                            DaysTillSprout = 4,
                            Enemies = "cabbage, broccoli, kale, brussel sprouts, cauliflower, collards, kholrabi, hyssop, turnip",
                            Notes = "full sun,  direct sow outdoors",
                            SeedName = "radish",
                            SqFootPlant = 16,
                            WaterInterval = 5,
                            Zone = "5, 6, 7, 8, 9"
                        },
                        new
                        {
                            SeedId = 4,
                            Companions = "borage, cucumber, dill, melon, marigold, pole beans, nasturtium",
                            DaysTillHarvest = 100,
                            DaysTillSprout = 14,
                            Enemies = "cabbage, broccoli, fennel, kale, pepper, eggplant, brussel sprouts, cauliflower, collards, kholrabi,",
                            Notes = "full sun, start indoors and transplant or direct seed outdoors",
                            SeedName = "corn",
                            SqFootPlant = 4,
                            WaterInterval = 5,
                            Zone = "4, 5, 6, 7, 8, 9"
                        },
                        new
                        {
                            SeedId = 5,
                            Companions = "cabbage, kale, cauliflower, collards, eggplant, leek, lettuce, brussels sprouts, kohlrabi, asparagus, strawberries, radish, beans, peas, nasturtium, petunia, marigold",
                            DaysTillHarvest = 45,
                            DaysTillSprout = 5,
                            Enemies = "sunflowers, fennel, pumpkins, melons, corn, potatoes",
                            Notes = "full sun, direct sow outdoors",
                            SeedName = "spinach",
                            SqFootPlant = 9,
                            WaterInterval = 2,
                            Zone = "2, 3, 4, 5, 6, 7, 8, 9"
                        },
                        new
                        {
                            SeedId = 6,
                            Companions = "chives, garlic, marigold, beet, carrot, parsnip, onion, strawberries, corn, eggplant, tomato, corn, asparagus, peas, radish",
                            DaysTillHarvest = 45,
                            DaysTillSprout = 10,
                            Enemies = "cabbage, broccoli, kale, brussel sprouts, cauliflower, collards, kholrabi",
                            Notes = "full sun, direct sow outdoors",
                            SeedName = "loose-leaf lettuce",
                            SqFootPlant = 4,
                            WaterInterval = 4,
                            Zone = "2, 3, 4, 5, 6, 7, 8, 9"
                        },
                        new
                        {
                            SeedId = 7,
                            Companions = "cabbage, broccoli, kale, brussel sprouts, cauliflower, collards, kholrabi, carrot, leek, beet, strawberries",
                            DaysTillHarvest = 90,
                            DaysTillSprout = 10,
                            Enemies = "peas, pole beans, bush beans, asparagus",
                            Notes = "full sun, direct sow or from bulb outdoors",
                            SeedName = "onion",
                            SqFootPlant = 4,
                            WaterInterval = 3,
                            Zone = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11"
                        },
                        new
                        {
                            SeedId = 8,
                            Companions = "peas, pole beans, bush beans, onions, leeks, chives, and garlic, cabbage, broccoli, cauliflower, carrots, kale, okra, spinach, sunflowers, lettuce, brussels sprouts",
                            DaysTillHarvest = 90,
                            DaysTillSprout = 12,
                            Enemies = "any new plants grown by seed (watermelons release chemicals that inhibit seed growth)",
                            Notes = "full sun, start indoors and transplant",
                            SeedName = "watermelon",
                            SqFootPlant = 1,
                            WaterInterval = 3,
                            Zone = "3, 4, 5, 6, 7, 8, 9, 10, 11"
                        },
                        new
                        {
                            SeedId = 9,
                            Companions = "corn, beans, radish, nasturtium, aromatic herbs",
                            DaysTillHarvest = 120,
                            DaysTillSprout = 10,
                            Enemies = "beet, onion, potato, cabbage, broccoli, kale, brussel sprouts, cauliflower, collards, kholrabi",
                            Notes = "full sun, direct sow outdoors",
                            SeedName = "pumpkin",
                            SqFootPlant = 1,
                            WaterInterval = 3,
                            Zone = "3, 4, 5, 6, 7"
                        });
                });

            modelBuilder.Entity("GardenAPI.Models.ZipZone", b =>
                {
                    b.Property<int>("ZipZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("ZipZoneId");

                    b.ToTable("ZipZones");
                });
#pragma warning restore 612, 618
        }
    }
}
